namespace Cnn.Common.Localization;

public sealed class MessageLocalizer : IMessageLocalizer
{
    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Messages =
        new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            {
                "zh-CN",
                new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
                {
                    ["success"] = "成功",
                    ["status.ok"] = "正常",
                    ["server-1"] = "服务器-1",
                    ["invalid_param"] = "参数非法",
                    ["missing_param"] = "缺少必填参数",
                    ["auth_invalid"] = "认证失败",
                    ["auth_expired"] = "认证已过期",
                    ["permission_denied"] = "权限不足",
                    ["not_found"] = "资源不存在",
                    ["already_exists"] = "资源已存在",
                    ["in_use"] = "资源被引用",
                    ["state_conflict"] = "状态冲突",
                    ["precondition_failed"] = "前置条件不足",
                    ["not_implemented"] = "暂未实现",
                    ["rate_limited"] = "请求过于频繁",
                    ["quota_exceeded"] = "配额耗尽",
                    ["internal_error"] = "内部错误",
                    ["db_error"] = "数据库错误",
                    ["config_error"] = "配置错误",
                    ["external_provider_error"] = "外部系统错误",
                    ["service_unavailable"] = "服务不可用",
                    ["task_queue_full"] = "任务队列拥塞",
                    ["timeout"] = "请求超时",
                    ["agent_offline"] = "节点离线",
                    ["agent_auth_failed"] = "节点认证失败",
                    ["agent_version_mismatch"] = "节点版本不匹配",
                    ["agent_task_reject"] = "节点拒绝任务",
                    ["ws_not_connected"] = "WS 未连接",
                    ["dns_sync_failed"] = "DNS 同步失败",
                    ["invalid_domain"] = "域名非法",
                    ["dns_provider_required"] = "DNS 服务商必填",
                    ["dns_provider_not_found"] = "DNS 服务商不存在",
                    ["dns_provider_in_use"] = "DNS 服务商被引用",
                    ["dns_provider_not_configured"] = "DNS 服务商未配置",
                    ["dns_provider_not_available"] = "DNS 服务商不可用",
                    ["dns_provider_type_invalid"] = "DNS 服务商类型非法",
                    ["invalid_credentials"] = "凭证非法",
                    ["invalid_credentials_format"] = "凭证格式非法",
                    ["invalid_credentials_required"] = "凭证字段缺失",
                    ["user_disabled"] = "用户已禁用",
                    ["invalid_captcha"] = "验证码错误",
                    ["captcha_not_enabled"] = "未开启验证码",
                    ["email_required_for_captcha"] = "登录验证需要邮箱",
                    ["phone_required_for_captcha"] = "登录验证需要手机号",
                    ["sms_not_configured"] = "短信验证未配置",
                    ["email_send_failed"] = "邮件发送失败",
                    ["captcha_store_failed"] = "验证码保存失败",
                    ["register_disabled"] = "已关闭注册",
                    ["user_exists"] = "用户已存在",
                    ["user_create_failed"] = "创建用户失败",
                    ["cname_domain_exists"] = "CNAME 域名已存在",
                    ["cname_domain_in_use"] = "CNAME 域名被引用",
                    ["cname_domain_check_failed"] = "CNAME 域名引用检查失败",
                    ["cname_domains_not_configured"] = "未配置 CNAME 域名",
                    ["invalid_json"] = "JSON 解析失败",
                    ["db_create_error"] = "数据库创建失败",
                    ["db_save_error"] = "数据库保存失败",
                    ["user_id_required"] = "用户ID必填",
                    ["order.purchase"] = "购买",
                    ["order.renew"] = "续费",
                    ["order.recharge"] = "充值",
                    ["order.other"] = "其他",
                    ["custom_cc_rule_not_enabled"] = "未开启自定义CC规则权限",
                    ["custom_cc_rule_check_failed"] = "检查自定义CC规则权限失败",
                    ["name_required"] = "名称必填",
                    ["domain_name_required"] = "域名名称必填",
                    ["domain_exists"] = "域名已存在",
                    ["domain_not_found"] = "域名不存在",
                    ["version_required"] = "版本号必填",
                    ["invalid_version_format"] = "版本号格式非法",
                    ["file_required"] = "文件必填",
                    ["invalid_file_type"] = "文件类型非法",
                    ["version_not_found"] = "版本不存在",
                    ["node_ids_required"] = "节点列表必填",
                    ["task_id_required"] = "task_id 必填",
                    ["task_not_found"] = "任务不存在",
                    ["task.type_invalid"] = "任务类型非法",
                    ["task.urls_required"] = "URL 列表不能为空",
                    ["task.url_invalid_prefix"] = "URL 必须以 http:// 或 https:// 开头",
                    ["task.url_invalid_format"] = "URL 格式不正确",
                    ["task.wildcard_invalid"] = "泛域名格式不正确",
                    ["task.domain_not_found"] = "域名不存在",
                    ["task.today_refresh_url_limit"] = "今日刷新 URL 次数不足",
                    ["task.today_refresh_dir_limit"] = "今日刷新目录次数不足",
                    ["task.today_preheat_limit"] = "今日预热次数不足",
                    ["task.refresh_url"] = "刷新URL",
                    ["task.refresh_dir"] = "刷新目录",
                    ["task.preheat"] = "预热",
                    ["task.failed_suffix"] = "任务失败",
                    ["task.done_suffix"] = "任务完成",
                    ["task.exec_success"] = "执行成功",
                    ["task.exec_failed"] = "执行失败",
                    ["task.reason_prefix"] = "，原因：",
                    ["task.url_prefix"] = "，URL：",
                    ["file_not_found"] = "文件不存在",
                    ["update_failed"] = "更新失败",
                    ["region_required"] = "区域必填",
                    ["region_not_found"] = "区域不存在",
                    ["line_group_required"] = "线路组必填",
                    ["line_group_not_found"] = "线路组不存在",
                    ["backup_group_conflict"] = "备用线路组不能与线路组相同",
                    ["plan_user_required"] = "plan_id 和 user_id 必填",
                    ["plan_not_found"] = "套餐不存在",
                    ["user_not_found"] = "用户不存在",
                    ["invalid_end_at"] = "end_at 时间格式不正确",
                    ["end_at_future"] = "end_at 必须是未来时间",
                    ["no_updates"] = "没有可更新字段",
                    ["ids_required"] = "ids 必填",
                    ["package_id_required"] = "package_id 必填",
                    ["package_not_found"] = "套餐不存在",
                    ["upgrade_disabled"] = "已关闭升级",
                    ["downgrade_disabled"] = "已关闭降级",
                    ["domain_limit_exceeded"] = "域名数量超限: {0}",
                    ["main_domain_limit_exceeded"] = "主域名数量超限: {0}",
                    ["listen_ports_required"] = "监听端口必填",
                    ["origin_required"] = "源站必填",
                    ["forward_not_found"] = "转发不存在",
                    ["forward_batch_data_required"] = "批量数据必填",
                    ["forward_batch_data_invalid"] = "批量数据格式错误",
                    ["forward_create_failed"] = "创建转发失败",
                    ["forward_cname_generate_failed"] = "生成转发 CNAME 失败",
                    ["forward_group_name_required"] = "转发分组名称必填",
                    ["forward_group_id_required"] = "转发分组 ID 必填",
                    ["site_group_id_required"] = "站点分组 ID 必填",
                    ["forward_default_key_required"] = "转发默认配置项必填",
                    ["forward_default_id_required"] = "转发默认配置 ID 必填",
                    ["no_forwards_available"] = "没有可用的转发",
                    ["unknown_action"] = "未知操作",
                    ["dnsapi_name_required"] = "DNSAPI 名称必填",
                    ["dnsapi_type_required"] = "DNSAPI 类型必填",
                    ["dnsapi_id_required"] = "DNSAPI ID 必填",
                    ["cert_type_required"] = "证书类型必填",
                    ["cert_upload_required"] = "上传证书需要证书内容与私钥",
                    ["cert_domain_required"] = "证书域名必填",
                    ["cert_invalid_id"] = "证书ID非法",
                    ["cert_not_found"] = "证书不存在",
                    ["cert_delete_failed"] = "证书删除失败",
                    ["cert_delete_success"] = "证书删除成功",
                    ["cert_action_failed"] = "证书操作失败",
                    ["cert_action_success"] = "证书操作成功",
                    ["cert_enable_failed"] = "证书启用失败",
                    ["cert_in_use_disable_first"] = "证书启用中，请先禁用",
                    ["cert_selected_enabled_disable_first"] = "选中的证书仍启用，请先禁用",
                    ["cert_site_ref_disable_first"] = "证书被站点引用，请先解除",
                    ["cert_unknown_action"] = "未知证书操作",
                    ["cert_parse_failed"] = "证书解析失败",
                    ["cert_batch_domains_required"] = "批量域名必填",
                    ["cert_wildcard_required"] = "泛域名必填",
                    ["wildcard_requires_dnsapi"] = "泛域名申请必须指定 DNSAPI",
                    ["dns_challenge_not_found"] = "DNS 验证信息不存在",
                    ["dns_txt_not_found"] = "DNS TXT 记录未生效",
                    ["acme_email_required"] = "ACME 邮箱必填",
                    ["cert_save_failed"] = "证书保存失败",
                    ["cert_update_failed"] = "证书更新失败",
                    ["cert_free"] = "免费证书",
                    ["token_required"] = "token 必填",
                    ["value_required"] = "value 必填",
                    ["message.package_expire"] = "套餐到期",
                    ["message.traffic_exceed"] = "流量超限",
                    ["message.conn_exceed"] = "连接超限",
                    ["message.bandwidth_exceed"] = "带宽超限",
                    ["message.rule_switch"] = "CC 规则开关",
                    ["message.cert_expire"] = "证书到期",
                    ["message.refresh_url"] = "URL 刷新",
                    ["message.refresh_dir"] = "目录刷新",
                    ["message.preheat"] = "预热",
                    ["message.other"] = "系统消息",
                    ["dashboard.auth_verified"] = "已实名认证",
                    ["dashboard.auth_unverified"] = "未实名认证",
                    ["agent.task_sync_package"] = "套餐同步",
                    ["task.sync_package_prefix"] = "同步套餐 package_id=",
                    ["upload_file_required"] = "请上传文件",
                    ["upload_image_only"] = "仅允许上传图片",
                    ["upload_save_failed"] = "文件保存失败"
                }
            },
            {
                "en-US",
                new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
                {
                    ["success"] = "Success",
                    ["status.ok"] = "OK",
                    ["server-1"] = "server-1",
                    ["invalid_param"] = "Invalid parameter",
                    ["missing_param"] = "Missing parameter",
                    ["auth_invalid"] = "Authentication failed",
                    ["auth_expired"] = "Authentication expired",
                    ["permission_denied"] = "Permission denied",
                    ["not_found"] = "Resource not found",
                    ["already_exists"] = "Resource already exists",
                    ["in_use"] = "Resource in use",
                    ["state_conflict"] = "State conflict",
                    ["precondition_failed"] = "Precondition failed",
                    ["not_implemented"] = "Not implemented",
                    ["rate_limited"] = "Rate limited",
                    ["quota_exceeded"] = "Quota exceeded",
                    ["internal_error"] = "Internal error",
                    ["db_error"] = "Database error",
                    ["config_error"] = "Configuration error",
                    ["external_provider_error"] = "External provider error",
                    ["service_unavailable"] = "Service unavailable",
                    ["task_queue_full"] = "Task queue full",
                    ["timeout"] = "Timeout",
                    ["agent_offline"] = "Agent offline",
                    ["agent_auth_failed"] = "Agent authentication failed",
                    ["agent_version_mismatch"] = "Agent version mismatch",
                    ["agent_task_reject"] = "Agent rejected task",
                    ["ws_not_connected"] = "WebSocket not connected",
                    ["dns_sync_failed"] = "DNS sync failed",
                    ["invalid_domain"] = "Invalid domain",
                    ["dns_provider_required"] = "DNS provider required",
                    ["dns_provider_not_found"] = "DNS provider not found",
                    ["dns_provider_in_use"] = "DNS provider in use",
                    ["dns_provider_not_configured"] = "DNS provider not configured",
                    ["dns_provider_not_available"] = "DNS provider not available",
                    ["dns_provider_type_invalid"] = "DNS provider type invalid",
                    ["invalid_credentials"] = "Invalid credentials",
                    ["invalid_credentials_format"] = "Invalid credentials format",
                    ["invalid_credentials_required"] = "Credentials fields required",
                    ["user_disabled"] = "User disabled",
                    ["invalid_captcha"] = "Invalid captcha",
                    ["captcha_not_enabled"] = "Captcha not enabled",
                    ["email_required_for_captcha"] = "Email is required for verification",
                    ["phone_required_for_captcha"] = "Phone is required for verification",
                    ["sms_not_configured"] = "SMS verification not configured",
                    ["email_send_failed"] = "Failed to send email",
                    ["captcha_store_failed"] = "Failed to store captcha",
                    ["register_disabled"] = "Registration disabled",
                    ["user_exists"] = "User already exists",
                    ["user_create_failed"] = "Failed to create user",
                    ["cname_domain_exists"] = "CNAME domain already exists",
                    ["cname_domain_in_use"] = "CNAME domain in use",
                    ["cname_domain_check_failed"] = "CNAME domain reference check failed",
                    ["cname_domains_not_configured"] = "CNAME domains not configured",
                    ["invalid_json"] = "Invalid JSON",
                    ["db_create_error"] = "Database create error",
                    ["db_save_error"] = "Database save error",
                    ["user_id_required"] = "User id is required",
                    ["order.purchase"] = "Purchase",
                    ["order.renew"] = "Renew",
                    ["order.recharge"] = "Recharge",
                    ["order.other"] = "Other",
                    ["custom_cc_rule_not_enabled"] = "Custom CC rule is not enabled",
                    ["custom_cc_rule_check_failed"] = "Failed to check custom CC rule permission",
                    ["name_required"] = "Name is required",
                    ["domain_name_required"] = "Domain name is required",
                    ["domain_exists"] = "Domain already exists",
                    ["domain_not_found"] = "Domain not found",
                    ["version_required"] = "Version is required",
                    ["invalid_version_format"] = "Invalid version format",
                    ["file_required"] = "File is required",
                    ["invalid_file_type"] = "Invalid file type",
                    ["version_not_found"] = "Version not found",
                    ["node_ids_required"] = "node_ids is required",
                    ["task_id_required"] = "task_id is required",
                    ["task_not_found"] = "Task not found",
                    ["task.type_invalid"] = "Invalid task type",
                    ["task.urls_required"] = "URLs cannot be empty",
                    ["task.url_invalid_prefix"] = "URL must start with http:// or https://",
                    ["task.url_invalid_format"] = "Invalid URL format",
                    ["task.wildcard_invalid"] = "Invalid wildcard domain",
                    ["task.domain_not_found"] = "Domain not found",
                    ["task.today_refresh_url_limit"] = "Today's refresh URL quota exceeded",
                    ["task.today_refresh_dir_limit"] = "Today's refresh directory quota exceeded",
                    ["task.today_preheat_limit"] = "Today's preheat quota exceeded",
                    ["task.refresh_url"] = "Refresh URL",
                    ["task.refresh_dir"] = "Refresh directory",
                    ["task.preheat"] = "Preheat",
                    ["task.failed_suffix"] = " failed",
                    ["task.done_suffix"] = " completed",
                    ["task.exec_success"] = "Execution succeeded",
                    ["task.exec_failed"] = "Execution failed",
                    ["task.reason_prefix"] = ", reason: ",
                    ["task.url_prefix"] = ", URL: ",
                    ["file_not_found"] = "File not found",
                    ["update_failed"] = "Update failed",
                    ["region_required"] = "Region is required",
                    ["region_not_found"] = "Region not found",
                    ["line_group_required"] = "Line group is required",
                    ["line_group_not_found"] = "Line group not found",
                    ["backup_group_conflict"] = "Backup group cannot equal line group",
                    ["plan_user_required"] = "plan_id and user_id are required",
                    ["plan_not_found"] = "Plan not found",
                    ["user_not_found"] = "User not found",
                    ["invalid_end_at"] = "Invalid end_at",
                    ["end_at_future"] = "end_at must be in the future",
                    ["no_updates"] = "No updates",
                    ["ids_required"] = "ids is required",
                    ["package_id_required"] = "package_id is required",
                    ["package_not_found"] = "Package not found",
                    ["upgrade_disabled"] = "Upgrade is disabled",
                    ["downgrade_disabled"] = "Downgrade is disabled",
                    ["domain_limit_exceeded"] = "Domain limit exceeded: {0}",
                    ["main_domain_limit_exceeded"] = "Main domain limit exceeded: {0}",
                    ["listen_ports_required"] = "Listen ports are required",
                    ["origin_required"] = "Origin is required",
                    ["forward_not_found"] = "Forward not found",
                    ["forward_batch_data_required"] = "Batch data is required",
                    ["forward_batch_data_invalid"] = "Batch data is invalid",
                    ["forward_create_failed"] = "Failed to create forward",
                    ["forward_cname_generate_failed"] = "Failed to generate forward CNAME",
                    ["forward_group_name_required"] = "Forward group name is required",
                    ["forward_group_id_required"] = "Forward group id is required",
                    ["site_group_id_required"] = "Site group ID is required",
                    ["forward_default_key_required"] = "Forward default key is required",
                    ["forward_default_id_required"] = "Forward default id is required",
                    ["no_forwards_available"] = "No forwards available",
                    ["unknown_action"] = "Unknown action",
                    ["dnsapi_name_required"] = "DNSAPI name is required",
                    ["dnsapi_type_required"] = "DNSAPI type is required",
                    ["dnsapi_id_required"] = "DNSAPI id is required",
                    ["cert_type_required"] = "Certificate type is required",
                    ["cert_upload_required"] = "Certificate and key are required for upload",
                    ["cert_domain_required"] = "Certificate domain is required",
                    ["cert_invalid_id"] = "Invalid certificate id",
                    ["cert_not_found"] = "Certificate not found",
                    ["cert_delete_failed"] = "Failed to delete certificate",
                    ["cert_delete_success"] = "Certificate deleted",
                    ["cert_action_failed"] = "Certificate action failed",
                    ["cert_action_success"] = "Certificate action succeeded",
                    ["cert_enable_failed"] = "Failed to enable certificate",
                    ["cert_in_use_disable_first"] = "Certificate is enabled, disable first",
                    ["cert_selected_enabled_disable_first"] = "Selected certificates are enabled, disable first",
                    ["cert_site_ref_disable_first"] = "Certificate is referenced by sites",
                    ["cert_unknown_action"] = "Unknown certificate action",
                    ["cert_parse_failed"] = "Failed to parse certificate",
                    ["cert_batch_domains_required"] = "Domains are required",
                    ["cert_wildcard_required"] = "Wildcard domain is required",
                    ["wildcard_requires_dnsapi"] = "Wildcard requires DNSAPI",
                    ["dns_challenge_not_found"] = "DNS challenge not found",
                    ["dns_txt_not_found"] = "DNS TXT record not found",
                    ["acme_email_required"] = "ACME email is required",
                    ["cert_save_failed"] = "Failed to save certificate",
                    ["cert_update_failed"] = "Failed to update certificate",
                    ["cert_free"] = "Free certificate",
                    ["token_required"] = "token is required",
                    ["value_required"] = "value is required",
                    ["message.package_expire"] = "Package expired",
                    ["message.traffic_exceed"] = "Traffic exceeded",
                    ["message.conn_exceed"] = "Connections exceeded",
                    ["message.bandwidth_exceed"] = "Bandwidth exceeded",
                    ["message.rule_switch"] = "CC rule switch",
                    ["message.cert_expire"] = "Certificate expired",
                    ["message.refresh_url"] = "URL refresh",
                    ["message.refresh_dir"] = "Directory refresh",
                    ["message.preheat"] = "Preheat",
                    ["message.other"] = "System message",
                    ["dashboard.auth_verified"] = "Verified",
                    ["dashboard.auth_unverified"] = "Unverified",
                    ["agent.task_sync_package"] = "Package sync",
                    ["task.sync_package_prefix"] = "Sync package package_id=",
                    ["upload_file_required"] = "File is required",
                    ["upload_image_only"] = "Only images are allowed",
                    ["upload_save_failed"] = "Failed to save file"
                }
            }
        };

    public string DefaultLanguage { get; } = "zh-CN";

    public string Translate(string key, string? language)
    {
        if (string.IsNullOrWhiteSpace(key))
        {
            return string.Empty;
        }

        var normalized = LanguageResolver.NormalizeOrDefault(language, DefaultLanguage);
        if (Messages.TryGetValue(normalized, out var table) && table.TryGetValue(key, out var value))
        {
            return value;
        }

        if (Messages.TryGetValue(DefaultLanguage, out var fallback) && fallback.TryGetValue(key, out var fallbackValue))
        {
            return fallbackValue;
        }

        return key;
    }
}
