SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `node_group` (
  `id` int NOT NULL,
  `region_id` bigint DEFAULT NULL,
  `cname_hostname` varchar(8) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `des` varchar(255) DEFAULT NULL,
  `backup_switch_type` varchar(20) DEFAULT NULL,
  `backup_switch_policy` varchar(80) DEFAULT NULL,
  `create_at` datetime DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `sort_order` int DEFAULT '100',
  `ipv4_resolution` varchar(255) DEFAULT '',
  `l2_config` varchar(255) DEFAULT '',
  `cname_domain` longtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `node` (
  `id` int NOT NULL,
  `pid` bigint DEFAULT NULL,
  `region_id` bigint DEFAULT NULL,
  `name` longtext,
  `des` longtext,
  `ip` varchar(191) DEFAULT NULL,
  `host` longtext,
  `port` bigint DEFAULT NULL,
  `http_proxy` longtext,
  `is_mgmt` tinyint(1) DEFAULT NULL,
  `create_at` datetime(3) DEFAULT NULL,
  `update_at` datetime(3) DEFAULT NULL,
  `enable` tinyint(1) DEFAULT NULL,
  `disable_by` longtext,
  `config_task` longtext,
  `check_on` tinyint(1) DEFAULT NULL,
  `check_protocol` longtext,
  `check_timeout` bigint DEFAULT NULL,
  `check_port` bigint DEFAULT NULL,
  `check_host` longtext,
  `check_path` longtext,
  `check_node_group` longtext,
  `check_action` longtext,
  `bw_limit` longtext,
  `p_id` bigint DEFAULT NULL,
  `token` varchar(255) DEFAULT NULL,
  `level` int DEFAULT '1',
  `sort` int DEFAULT '0',
  `cache_dir` longtext,
  `max_cache_size` bigint DEFAULT NULL,
  `log_dir` longtext,
  `ssh_host` varchar(255) DEFAULT NULL,
  `ssh_port` int DEFAULT '22',
  `ssh_user` varchar(255) DEFAULT NULL,
  `ssh_auth_type` varchar(20) DEFAULT NULL,
  `ssh_password` varchar(255) DEFAULT NULL,
  `ssh_key` longtext,
  `work_dir` varchar(255) DEFAULT NULL,
  `auto_install` tinyint(1) DEFAULT '0',
  `install_status` varchar(20) DEFAULT 'idle',
  `install_error` text,
  `install_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `line` (
  `id` int NOT NULL,
  `node_group_id` int DEFAULT NULL,
  `node_id` int DEFAULT NULL,
  `node_ip_id` int DEFAULT NULL,
  `line_id` varchar(255) DEFAULT NULL,
  `line_name` varchar(255) DEFAULT NULL,
  `weight` varchar(4) DEFAULT NULL,
  `create_at` datetime DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `record_id` varchar(255) DEFAULT NULL,
  `task_id` bigint DEFAULT NULL,
  `enable` tinyint(1) DEFAULT NULL,
  `is_backup` tinyint(1) DEFAULT NULL,
  `enable_backup` tinyint(1) DEFAULT NULL,
  `is_backup_default_line` tinyint(1) DEFAULT NULL,
  `enable_backup_default_line` tinyint(1) DEFAULT NULL,
  `switch_at` datetime DEFAULT NULL,
  `disable_by` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `site` (
  `id` int NOT NULL,
  `uid` int DEFAULT NULL,
  `user_package` int DEFAULT NULL,
  `region_id` int DEFAULT NULL,
  `node_group_id` int DEFAULT NULL,
  `backup_node_group` int DEFAULT NULL,
  `enable_backup_group` tinyint(1) DEFAULT NULL,
  `cname_domain` varchar(255) DEFAULT NULL,
  `cname_hostname2` varchar(255) DEFAULT NULL,
  `cname_mode` varchar(10) DEFAULT NULL,
  `cname_hostname` varchar(255) DEFAULT NULL,
  `domain` text,
  `http_listen` text,
  `https_listen` text,
  `balance_way` varchar(255) DEFAULT NULL,
  `backend` text,
  `backend_protocol` varchar(32) DEFAULT 'follow',
  `backend_https_port` varchar(5) DEFAULT NULL,
  `backend_http_port` varchar(5) DEFAULT NULL,
  `proxy_timeout` varchar(3) DEFAULT NULL,
  `backend_port_mapping` tinyint(1) DEFAULT NULL,
  `health_check` varchar(255) DEFAULT NULL,
  `ups_keepalive` tinyint(1) DEFAULT NULL,
  `ups_keepalive_conn` int DEFAULT NULL,
  `ups_keepalive_timeout` int DEFAULT NULL,
  `proxy_http_version` varchar(3) DEFAULT NULL,
  `proxy_ssl_protocols` varchar(255) DEFAULT NULL,
  `backend_host` varchar(255) DEFAULT NULL,
  `range` tinyint(1) DEFAULT NULL,
  `proxy_cache` text,
  `cc_default_rule` int DEFAULT NULL,
  `cc_switch` text,
  `extra_cc_rule` text,
  `block_proxy` tinyint(1) DEFAULT NULL,
  `block_region` text,
  `black_ip` text,
  `white_ip` text,
  `spider_allow` varchar(255) DEFAULT NULL,
  `acl` int DEFAULT NULL,
  `hotlink` text,
  `cors` text,
  `resp_header` text,
  `req_header` text,
  `page_404` text,
  `page_50x` text,
  `url_rewrite` text,
  `gzip_enable` tinyint(1) DEFAULT NULL,
  `gzip_types` varchar(255) DEFAULT NULL,
  `websocket_enable` tinyint(1) DEFAULT NULL,
  `acme_proxy_to_orgin` tinyint(1) DEFAULT NULL,
  `post_size_limit` int DEFAULT NULL,
  `create_at` datetime DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `version` int DEFAULT NULL,
  `enable` tinyint(1) DEFAULT NULL,
  `task_id` bigint DEFAULT NULL,
  `cname_task_id` bigint DEFAULT NULL,
  `record_id` varchar(255) DEFAULT NULL,
  `state` varchar(255) DEFAULT NULL,
  `dns_provider_id` bigint DEFAULT NULL,
  `settings` longtext,
  `platform_dns_record_id` varchar(64) DEFAULT NULL,
  `user_dns_record_id` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `cc_rule` (
  `id` int NOT NULL,
  `sort` int DEFAULT NULL,
  `uid` int DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `des` varchar(255) DEFAULT NULL,
  `data` longtext,
  `internal` tinyint(1) DEFAULT NULL,
  `enable` tinyint(1) DEFAULT NULL,
  `is_show` tinyint(1) DEFAULT NULL,
  `task_id` bigint DEFAULT NULL,
  `version` int DEFAULT NULL,
  `create_at` datetime DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `cc_match` (
  `id` int NOT NULL,
  `uid` int DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `des` varchar(255) DEFAULT NULL,
  `data` mediumtext,
  `internal` tinyint(1) DEFAULT NULL,
  `enable` tinyint(1) DEFAULT NULL,
  `task_id` bigint DEFAULT NULL,
  `version` int DEFAULT NULL,
  `create_at` datetime DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `cc_filter` (
  `id` int NOT NULL,
  `uid` int DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `des` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `within_second` int DEFAULT NULL,
  `max_req` int DEFAULT NULL,
  `max_req_per_uri` int DEFAULT NULL,
  `extra` text,
  `internal` tinyint(1) DEFAULT NULL,
  `enable` tinyint(1) DEFAULT NULL,
  `task_id` bigint DEFAULT NULL,
  `version` int DEFAULT NULL,
  `create_at` datetime DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `acl` (
  `id` int NOT NULL,
  `uid` int DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `des` varchar(255) DEFAULT NULL,
  `default_action` varchar(255) DEFAULT NULL,
  `data` mediumtext,
  `create_at` datetime DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `enable` tinyint(1) DEFAULT NULL,
  `task_id` bigint DEFAULT NULL,
  `version` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `config` (
  `name` varchar(255) DEFAULT NULL,
  `value` longtext,
  `type` varchar(100) DEFAULT NULL,
  `scope_id` bigint DEFAULT NULL,
  `scope_name` varchar(100) DEFAULT NULL,
  `create_at` datetime(3) DEFAULT NULL,
  `update_at` datetime(3) DEFAULT NULL,
  `enable` tinyint(1) DEFAULT NULL,
  `task_id` bigint DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;
