upstream stream_up_14 {
    server 202.73.4.80:39091 weight=1;
}
server {
    listen 39100 proxy_protocol;
    proxy_pass stream_up_14;
    proxy_connect_timeout 10s;
    proxy_timeout 60s;
}
upstream stream_up_24 {
    server 1.1.1.1:8080 weight=1;
}
server {
    listen 20357 proxy_protocol;
    proxy_pass stream_up_24;
    proxy_connect_timeout 10s;
    proxy_timeout 60s;
}
